server:
  port: '8081'
  servlet:
    context-path: /api/sensors

spring:
  application.name: temperature-processing
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq